[build.environment]
GO_VERSION = "1.24.2"
HUGO_VERSION = "0.148.0"
TZ = "Europe/London"

[build]
publish = "public"
command = "git config core.quotepath false && hugo --gc --minify"

# Prevent indexing of deploy previews
[[headers]]
for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex"
  [headers.conditions]
    Environment = "deploy-preview"

# Security + GA4-compatible CSP headers
[[headers]]
for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src * data:; connect-src https://*.google-analytics.com;"