[build.environment]
GO_VERSION = "1.24.2"
HUGO_VERSION = "0.148.0"
TZ = "Europe/London"

[build]
publish = "public"
command = "git config core.quotepath false && hugo --gc --minify"

[[functions]]
  schedule = "0 1 * * *" # every night at 1am UTC
  name = "nightly-build"